version: "3.1"

services:
  backend:
    container_name: "backend"
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - mygame_db
    build:
      dockerfile: Dockerfile
      context: ./backend
    command: npm run dev
    environment:
      - MYSQL_DATABASE=mygame_db
      - MYSQL_ROOT_PASSWORD=mygameroot
      - MYSQL_USER=root
      - MYSQL_LOCALHOST=mygame_db
      - MYSQL_PORT=3306
      - API_PORT=3333
      - CLIENT_URL=http://154.53.35.101:8080
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USER=easysaleproject@gmail.com
      - MAIL_PASSWORD=nvemoxkcqxxxpawi
      - SECRET_KEY=7895d135d8c67f8908db131cf1b4f530

  migration:
    container_name: "migration"
    depends_on:
      - mygame_db
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run migration:run
    environment:
      - MYSQL_DATABASE=mygame_db
      - MYSQL_ROOT_PASSWORD=mygameroot
      - MYSQL_USER=root
      - MYSQL_LOCALHOST=mygame_db
      - MYSQL_PORT=3306
      - API_PORT=3333
      - CLIENT_URL=http://154.53.35.101:8080
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USER=easysaleproject@gmail.com
      - MAIL_PASSWORD=nvemoxkcqxxxpawi
      - SECRET_KEY=7895d135d8c67f8908db131cf1b4f530

  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
      - mygame_db
    ports:
      - 8080:3000
    environment:
      - REACT_APP_API_URL=http://154.53.35.101:3333
      - REACT_APP_NAME_STORAGE=@MyGame

  mygame_db:
    container_name: "mygame_db"
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mygame_db
      MYSQL_ROOT_PASSWORD: mygameroot

networks:
  default:
    name: web
