version: '3.1'

services:
  mygame_db:
    container_name: 'mygame_db'
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: mygame_db
      MYSQL_ROOT_PASSWORD: mygameroot
